steps:
  # Inject GA Measurement ID from Secret Manager
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        GA_ID=$(gcloud secrets versions access latest --secret=ga-homepage --project=$PROJECT_ID)
        find frontend -name "*.html" -exec sed -i "s/%%GA_MEASUREMENT_ID%%/$${GA_ID}/g" {} \;
        find frontend -name "*.js" -exec sed -i "s/%%GA_MEASUREMENT_ID%%/$${GA_ID}/g" {} \;
    id: InjectGA

  # Sync frontend files to GCS bucket
  - name: 'gcr.io/cloud-builders/gsutil'
    args:
      - '-m'
      - 'rsync'
      - '-r'
      - '-d'
      - 'frontend/'
      - 'gs://${_BUCKET_NAME}/'
    id: Sync

  # Set Cache-Control for HTML files (1 hour)
  - name: 'gcr.io/cloud-builders/gsutil'
    args:
      - '-m'
      - 'setmeta'
      - '-h'
      - 'Cache-Control:public, max-age=3600'
      - 'gs://${_BUCKET_NAME}/**/*.html'
    id: CacheHTML

  # Set Cache-Control for CSS/JS files (1 year)
  - name: 'gcr.io/cloud-builders/gsutil'
    args:
      - '-m'
      - 'setmeta'
      - '-h'
      - 'Cache-Control:public, max-age=31536000'
      - 'gs://${_BUCKET_NAME}/**/*.css'
    id: CacheCSS

  - name: 'gcr.io/cloud-builders/gsutil'
    args:
      - '-m'
      - 'setmeta'
      - '-h'
      - 'Cache-Control:public, max-age=31536000'
      - 'gs://${_BUCKET_NAME}/**/*.js'
    id: CacheJS

  # Set Cache-Control for SVG files (1 year)
  - name: 'gcr.io/cloud-builders/gsutil'
    args:
      - '-m'
      - 'setmeta'
      - '-h'
      - 'Cache-Control:public, max-age=31536000'
      - '-h'
      - 'Content-Type:image/svg+xml'
      - 'gs://${_BUCKET_NAME}/**/*.svg'
    id: CacheSVG

  # Set Cache-Control for JSON files (1 day)
  - name: 'gcr.io/cloud-builders/gsutil'
    args:
      - '-m'
      - 'setmeta'
      - '-h'
      - 'Cache-Control:public, max-age=86400'
      - '-h'
      - 'Content-Type:application/json'
      - 'gs://${_BUCKET_NAME}/**/*.json'
    id: CacheJSON

  # Set Cache-Control for sitemap and robots (1 day)
  - name: 'gcr.io/cloud-builders/gsutil'
    args:
      - '-m'
      - 'setmeta'
      - '-h'
      - 'Cache-Control:public, max-age=86400'
      - 'gs://${_BUCKET_NAME}/sitemap.xml'
    id: CacheSitemap

  - name: 'gcr.io/cloud-builders/gsutil'
    args:
      - '-m'
      - 'setmeta'
      - '-h'
      - 'Cache-Control:public, max-age=86400'
      - 'gs://${_BUCKET_NAME}/robots.txt'
    id: CacheRobots

substitutions:
  _BUCKET_NAME: aiinpocket.com

options:
  logging: CLOUD_LOGGING_ONLY
